server:
  port: 8080

spring:
  application:
    name: mall-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}:${spring.cloud.client.hostname}

#my:
#  name: zhaiyujia
