spring:
  config:
    import: optional:consul:localhost:8500
  profiles:
    active: dev
  application:
    name: mall-order
  cloud:
    consul:
    # 配置中心相关配置
      config:
        enabled: true #是否启用配置中心功能
        format: yaml #设置配置值的格式
        prefixes: config #设置配置所在目录
        data-key: data #配置key的名字，由于Consul是K/V存储，配置存储在对应K的V中
        watch:
          # 是否开启自动刷新，默认值 true 开启
          enabled: true
          # 刷新频率，单位：毫秒，默认值 1000
          delay: 1000
        profile-separator: "-"
#      # 服务发现相关配置
#      discovery:
#        register: true                                # 是否需要注册
#        service-name: ${spring.application.name}      # 服务名称
#        port: ${server.port}                          # 服务端口
#        prefer-ip-address: true                       # 是否使用 ip 地址注册
      # 服务发现相关配置
      discovery:
        register: true                                # 是否需要注册
        service-name: ${spring.application.name}      # 服务名称
        port: ${server.port}                          # 服务端口
        instance-id: ${spring.application.name}:${server.port}:${spring.cloud.client.ip-address}